# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addDataDialog_1.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addDataDialog(object):
    def setupUi(self, addDataDialog):
        addDataDialog.setObjectName("addDataDialog")
        addDataDialog.resize(692, 527)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(addDataDialog)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(addDataDialog)
        self.label.setMinimumSize(QtCore.QSize(162, 0))
        self.label.setMaximumSize(QtCore.QSize(162, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(addDataDialog)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(addDataDialog)
        self.label_2.setMinimumSize(QtCore.QSize(162, 0))
        self.label_2.setMaximumSize(QtCore.QSize(162, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(addDataDialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(addDataDialog)
        self.label_3.setMinimumSize(QtCore.QSize(162, 0))
        self.label_3.setMaximumSize(QtCore.QSize(162, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(addDataDialog)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(addDataDialog)
        self.label_4.setMinimumSize(QtCore.QSize(162, 0))
        self.label_4.setMaximumSize(QtCore.QSize(162, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(addDataDialog)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(addDataDialog)
        self.label_5.setMinimumSize(QtCore.QSize(162, 0))
        self.label_5.setMaximumSize(QtCore.QSize(162, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(addDataDialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(addDataDialog)
        self.label_6.setMinimumSize(QtCore.QSize(162, 0))
        self.label_6.setMaximumSize(QtCore.QSize(162, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.dateEdit = QtWidgets.QDateEdit(addDataDialog)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_6.addWidget(self.dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(addDataDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)

        self.retranslateUi(addDataDialog)
        self.buttonBox.accepted.connect(addDataDialog.accept)
        self.buttonBox.rejected.connect(addDataDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(addDataDialog)

    def retranslateUi(self, addDataDialog):
        _translate = QtCore.QCoreApplication.translate
        addDataDialog.setWindowTitle(_translate("addDataDialog", "添加运行记录"))
        self.label.setText(_translate("addDataDialog", "运行时间/h："))
        self.label_2.setText(_translate("addDataDialog", "环境温度/℃："))
        self.label_3.setText(_translate("addDataDialog", "刀头温度/℃："))
        self.label_4.setText(_translate("addDataDialog", "重复定位精度/μm："))
        self.label_5.setText(_translate("addDataDialog", "轴向："))
        self.comboBox.setItemText(0, _translate("addDataDialog", "X"))
        self.comboBox.setItemText(1, _translate("addDataDialog", "Y"))
        self.comboBox.setItemText(2, _translate("addDataDialog", "Z"))
        self.label_6.setText(_translate("addDataDialog", "测试日期："))


