# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reliability_main.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtChart import QChartView

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1204, 875)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1176, 788))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget)
        self.manaDevButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.manaDevButton.setObjectName("manaDevButton")
        self.verticalLayout_2.addWidget(self.manaDevButton)
        self.devComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.devComboBox.setObjectName("devComboBox")
        self.devComboBox.addItem("")
        self.verticalLayout_2.addWidget(self.devComboBox)
        self.devWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.devWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.devWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.devWidget.setObjectName("devWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.devWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.devWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.devWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.devWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.devWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.devWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.devWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.devWidget)
        self.devComboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.devComboBox_2.setObjectName("devComboBox_2")
        self.devComboBox_2.addItem("")
        self.verticalLayout_2.addWidget(self.devComboBox_2)
        self.devWidget_2 = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.devWidget_2.setMinimumSize(QtCore.QSize(100, 0))
        self.devWidget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.devWidget_2.setObjectName("devWidget_2")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.devWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.devWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.devWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.devWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.devWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.devWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.devWidget_2.addItem(item)
        self.verticalLayout_2.addWidget(self.devWidget_2)
        self.horizontalLayout_23.addLayout(self.verticalLayout_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.setObjectName("stackedWidget")
        self.reliaPage = QtWidgets.QWidget()
        self.reliaPage.setObjectName("reliaPage")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.reliaPage)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.reliaPage)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.reliaPage)
        self.label_4.setMinimumSize(QtCore.QSize(60, 0))
        self.label_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.tempEdit = QtWidgets.QLineEdit(self.reliaPage)
        self.tempEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.tempEdit.setMaximumSize(QtCore.QSize(210, 16777215))
        self.tempEdit.setObjectName("tempEdit")
        self.horizontalLayout_5.addWidget(self.tempEdit)
        self.label_5 = QtWidgets.QLabel(self.reliaPage)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.reliaPage)
        self.label_6.setMinimumSize(QtCore.QSize(60, 0))
        self.label_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.precEdit = QtWidgets.QLineEdit(self.reliaPage)
        self.precEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.precEdit.setMaximumSize(QtCore.QSize(210, 16777215))
        self.precEdit.setObjectName("precEdit")
        self.horizontalLayout_12.addWidget(self.precEdit)
        self.label_7 = QtWidgets.QLabel(self.reliaPage)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_19.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.outputDataButton = QtWidgets.QPushButton(self.reliaPage)
        self.outputDataButton.setObjectName("outputDataButton")
        self.gridLayout.addWidget(self.outputDataButton, 0, 0, 1, 1)
        self.loadButton = QtWidgets.QPushButton(self.reliaPage)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout.addWidget(self.loadButton, 0, 1, 1, 2)
        self.manaRecButton = QtWidgets.QPushButton(self.reliaPage)
        self.manaRecButton.setObjectName("manaRecButton")
        self.gridLayout.addWidget(self.manaRecButton, 0, 3, 1, 2)
        self.saveButton = QtWidgets.QPushButton(self.reliaPage)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 0, 5, 1, 1)
        self.rawDataButton = QtWidgets.QPushButton(self.reliaPage)
        self.rawDataButton.setObjectName("rawDataButton")
        self.gridLayout.addWidget(self.rawDataButton, 1, 0, 1, 2)
        self.scatterButton = QtWidgets.QPushButton(self.reliaPage)
        self.scatterButton.setObjectName("scatterButton")
        self.gridLayout.addWidget(self.scatterButton, 1, 2, 1, 2)
        self.reliaButton = QtWidgets.QPushButton(self.reliaPage)
        self.reliaButton.setObjectName("reliaButton")
        self.gridLayout.addWidget(self.reliaButton, 1, 4, 1, 2)
        self.horizontalLayout_19.addLayout(self.gridLayout)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.reliaWidget = QtWidgets.QStackedWidget(self.reliaPage)
        self.reliaWidget.setObjectName("reliaWidget")
        self.rawPage = QtWidgets.QWidget()
        self.rawPage.setObjectName("rawPage")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.rawPage)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.rawPage)
        self.label_10.setMinimumSize(QtCore.QSize(0, 0))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.axisComboBox = QtWidgets.QComboBox(self.rawPage)
        self.axisComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.axisComboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.axisComboBox.setObjectName("axisComboBox")
        self.axisComboBox.addItem("")
        self.axisComboBox.addItem("")
        self.axisComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.axisComboBox)
        self.label_11 = QtWidgets.QLabel(self.rawPage)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tempView_1 = QChartView(self.rawPage)
        self.tempView_1.setObjectName("tempView_1")
        self.gridLayout_3.addWidget(self.tempView_1, 0, 0, 1, 1)
        self.tempView_2 = QChartView(self.rawPage)
        self.tempView_2.setObjectName("tempView_2")
        self.gridLayout_3.addWidget(self.tempView_2, 0, 1, 1, 1)
        self.rpaView = QChartView(self.rawPage)
        self.rpaView.setObjectName("rpaView")
        self.gridLayout_3.addWidget(self.rpaView, 1, 0, 1, 1)
        self.straView = QChartView(self.rawPage)
        self.straView.setObjectName("straView")
        self.gridLayout_3.addWidget(self.straView, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_3)
        self.horizontalLayout_18.addLayout(self.verticalLayout_8)
        self.reliaWidget.addWidget(self.rawPage)
        self.scatterPage = QtWidgets.QWidget()
        self.scatterPage.setObjectName("scatterPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scatterPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scatterView = QChartView(self.scatterPage)
        self.scatterView.setObjectName("scatterView")
        self.horizontalLayout_2.addWidget(self.scatterView)
        self.reliaWidget.addWidget(self.scatterPage)
        self.resultPage = QtWidgets.QWidget()
        self.resultPage.setObjectName("resultPage")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.resultPage)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.resultPage)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.resultPage)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.reliaView = QChartView(self.resultPage)
        self.reliaView.setObjectName("reliaView")
        self.gridLayout_2.addWidget(self.reliaView, 1, 0, 1, 1)
        self.cdfView = QChartView(self.resultPage)
        self.cdfView.setObjectName("cdfView")
        self.gridLayout_2.addWidget(self.cdfView, 0, 1, 1, 1)
        self.failView = QChartView(self.resultPage)
        self.failView.setObjectName("failView")
        self.gridLayout_2.addWidget(self.failView, 1, 1, 1, 1)
        self.pdfView = QChartView(self.resultPage)
        self.pdfView.setObjectName("pdfView")
        self.gridLayout_2.addWidget(self.pdfView, 0, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_2)
        self.horizontalLayout_21.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.nextResultButton = QtWidgets.QPushButton(self.resultPage)
        self.nextResultButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.nextResultButton.setObjectName("nextResultButton")
        self.verticalLayout_10.addWidget(self.nextResultButton)
        self.reliaResultWidget = QtWidgets.QStackedWidget(self.resultPage)
        self.reliaResultWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.reliaResultWidget.setObjectName("reliaResultWidget")
        self.dev1Page = QtWidgets.QWidget()
        self.dev1Page.setObjectName("dev1Page")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.dev1Page)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dev1ResultWidget = QtWidgets.QListWidget(self.dev1Page)
        self.dev1ResultWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.dev1ResultWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.dev1ResultWidget.setObjectName("dev1ResultWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1ResultWidget.addItem(item)
        self.horizontalLayout_8.addWidget(self.dev1ResultWidget)
        self.reliaResultWidget.addWidget(self.dev1Page)
        self.dev2Page = QtWidgets.QWidget()
        self.dev2Page.setObjectName("dev2Page")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.dev2Page)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.dev2ResultWidget = QtWidgets.QListWidget(self.dev2Page)
        self.dev2ResultWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.dev2ResultWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.dev2ResultWidget.setObjectName("dev2ResultWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2ResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2ResultWidget.addItem(item)
        self.horizontalLayout_10.addWidget(self.dev2ResultWidget)
        self.reliaResultWidget.addWidget(self.dev2Page)
        self.cmpPage = QtWidgets.QWidget()
        self.cmpPage.setObjectName("cmpPage")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.cmpPage)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.cmpResultWidget = QtWidgets.QListWidget(self.cmpPage)
        self.cmpResultWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.cmpResultWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cmpResultWidget.setObjectName("cmpResultWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.cmpResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.cmpResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cmpResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.cmpResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cmpResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.cmpResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cmpResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.cmpResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cmpResultWidget.addItem(item)
        self.horizontalLayout_20.addWidget(self.cmpResultWidget)
        self.reliaResultWidget.addWidget(self.cmpPage)
        self.verticalLayout_10.addWidget(self.reliaResultWidget)
        self.horizontalLayout_21.addLayout(self.verticalLayout_10)
        self.verticalLayout_14.addLayout(self.horizontalLayout_21)
        self.reliaWidget.addWidget(self.resultPage)
        self.verticalLayout_9.addWidget(self.reliaWidget)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        self.manaRecButton.raise_()
        self.label_3.raise_()
        self.stackedWidget.addWidget(self.reliaPage)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.manaMtRecButton = QtWidgets.QPushButton(self.page)
        self.manaMtRecButton.setObjectName("manaMtRecButton")
        self.horizontalLayout_4.addWidget(self.manaMtRecButton)
        self.loadButton_2 = QtWidgets.QPushButton(self.page)
        self.loadButton_2.setObjectName("loadButton_2")
        self.horizontalLayout_4.addWidget(self.loadButton_2)
        self.outputDataButton_2 = QtWidgets.QPushButton(self.page)
        self.outputDataButton_2.setObjectName("outputDataButton_2")
        self.horizontalLayout_4.addWidget(self.outputDataButton_2)
        self.scatterButton_2 = QtWidgets.QPushButton(self.page)
        self.scatterButton_2.setObjectName("scatterButton_2")
        self.horizontalLayout_4.addWidget(self.scatterButton_2)
        self.reliaButton_2 = QtWidgets.QPushButton(self.page)
        self.reliaButton_2.setObjectName("reliaButton_2")
        self.horizontalLayout_4.addWidget(self.reliaButton_2)
        self.saveButton_2 = QtWidgets.QPushButton(self.page)
        self.saveButton_2.setObjectName("saveButton_2")
        self.horizontalLayout_4.addWidget(self.saveButton_2)
        self.verticalLayout_19.addLayout(self.horizontalLayout_4)
        self.maintainWidget = QtWidgets.QStackedWidget(self.page)
        self.maintainWidget.setObjectName("maintainWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.scatterView_2 = QChartView(self.page_3)
        self.scatterView_2.setObjectName("scatterView_2")
        self.horizontalLayout_9.addWidget(self.scatterView_2)
        self.maintainWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.page_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.page_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_2)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout_17.addLayout(self.horizontalLayout_11)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pdfView_2 = QChartView(self.page_4)
        self.pdfView_2.setObjectName("pdfView_2")
        self.gridLayout_5.addWidget(self.pdfView_2, 0, 0, 1, 1)
        self.cdfView_2 = QChartView(self.page_4)
        self.cdfView_2.setObjectName("cdfView_2")
        self.gridLayout_5.addWidget(self.cdfView_2, 0, 1, 1, 1)
        self.reliaView_2 = QChartView(self.page_4)
        self.reliaView_2.setObjectName("reliaView_2")
        self.gridLayout_5.addWidget(self.reliaView_2, 1, 0, 1, 1)
        self.failView_2 = QChartView(self.page_4)
        self.failView_2.setObjectName("failView_2")
        self.gridLayout_5.addWidget(self.failView_2, 1, 1, 1, 1)
        self.verticalLayout_17.addLayout(self.gridLayout_5)
        self.horizontalLayout_15.addLayout(self.verticalLayout_17)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.nextMtResultButton = QtWidgets.QPushButton(self.page_4)
        self.nextMtResultButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.nextMtResultButton.setObjectName("nextMtResultButton")
        self.verticalLayout_16.addWidget(self.nextMtResultButton)
        self.mtResultWidget = QtWidgets.QStackedWidget(self.page_4)
        self.mtResultWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mtResultWidget.setObjectName("mtResultWidget")
        self.dev1MtPage = QtWidgets.QWidget()
        self.dev1MtPage.setObjectName("dev1MtPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dev1MtPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dev1MtResultWidget = QtWidgets.QListWidget(self.dev1MtPage)
        self.dev1MtResultWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.dev1MtResultWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.dev1MtResultWidget.setObjectName("dev1MtResultWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev1MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev1MtResultWidget.addItem(item)
        self.verticalLayout_4.addWidget(self.dev1MtResultWidget)
        self.mtResultWidget.addWidget(self.dev1MtPage)
        self.dev2MtPage = QtWidgets.QWidget()
        self.dev2MtPage.setObjectName("dev2MtPage")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.dev2MtPage)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.dev2MtResultWidget = QtWidgets.QListWidget(self.dev2MtPage)
        self.dev2MtResultWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.dev2MtResultWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.dev2MtResultWidget.setObjectName("dev2MtResultWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.dev2MtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dev2MtResultWidget.addItem(item)
        self.verticalLayout_13.addWidget(self.dev2MtResultWidget)
        self.mtResultWidget.addWidget(self.dev2MtPage)
        self.cmpMtPage = QtWidgets.QWidget()
        self.cmpMtPage.setObjectName("cmpMtPage")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.cmpMtPage)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.cmpMtResultWidget = QtWidgets.QListWidget(self.cmpMtPage)
        self.cmpMtResultWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.cmpMtResultWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cmpMtResultWidget.setObjectName("cmpMtResultWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.cmpMtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.cmpMtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cmpMtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.cmpMtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cmpMtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.cmpMtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cmpMtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.cmpMtResultWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.cmpMtResultWidget.addItem(item)
        self.verticalLayout_15.addWidget(self.cmpMtResultWidget)
        self.mtResultWidget.addWidget(self.cmpMtPage)
        self.verticalLayout_16.addWidget(self.mtResultWidget)
        self.horizontalLayout_15.addLayout(self.verticalLayout_16)
        self.verticalLayout_18.addLayout(self.horizontalLayout_15)
        self.maintainWidget.addWidget(self.page_4)
        self.verticalLayout_19.addWidget(self.maintainWidget)
        self.horizontalLayout_22.addLayout(self.verticalLayout_19)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.addDataButton_3 = QtWidgets.QPushButton(self.page_2)
        self.addDataButton_3.setObjectName("addDataButton_3")
        self.horizontalLayout_7.addWidget(self.addDataButton_3)
        self.loadButton_3 = QtWidgets.QPushButton(self.page_2)
        self.loadButton_3.setObjectName("loadButton_3")
        self.horizontalLayout_7.addWidget(self.loadButton_3)
        self.outputDataButton_3 = QtWidgets.QPushButton(self.page_2)
        self.outputDataButton_3.setObjectName("outputDataButton_3")
        self.horizontalLayout_7.addWidget(self.outputDataButton_3)
        self.wholeButton = QtWidgets.QPushButton(self.page_2)
        self.wholeButton.setObjectName("wholeButton")
        self.horizontalLayout_7.addWidget(self.wholeButton)
        self.subSysButton = QtWidgets.QPushButton(self.page_2)
        self.subSysButton.setObjectName("subSysButton")
        self.horizontalLayout_7.addWidget(self.subSysButton)
        self.saveButton_3 = QtWidgets.QPushButton(self.page_2)
        self.saveButton_3.setObjectName("saveButton_3")
        self.horizontalLayout_7.addWidget(self.saveButton_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.faultWidget = QtWidgets.QStackedWidget(self.page_2)
        self.faultWidget.setObjectName("faultWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem3 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.label_8 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        spacerItem4 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pattView = QChartView(self.page_5)
        self.pattView.setObjectName("pattView")
        self.gridLayout_4.addWidget(self.pattView, 0, 0, 1, 1)
        self.posiView = QChartView(self.page_5)
        self.posiView.setObjectName("posiView")
        self.gridLayout_4.addWidget(self.posiView, 0, 1, 1, 1)
        self.resultWidget_3 = QtWidgets.QListWidget(self.page_5)
        self.resultWidget_3.setMinimumSize(QtCore.QSize(150, 0))
        self.resultWidget_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.resultWidget_3.setObjectName("resultWidget_3")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.resultWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resultWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.resultWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resultWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.resultWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resultWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.resultWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resultWidget_3.addItem(item)
        self.gridLayout_4.addWidget(self.resultWidget_3, 0, 2, 2, 1)
        self.reasonView = QChartView(self.page_5)
        self.reasonView.setObjectName("reasonView")
        self.gridLayout_4.addWidget(self.reasonView, 1, 0, 1, 1)
        self.rootView = QChartView(self.page_5)
        self.rootView.setObjectName("rootView")
        self.gridLayout_4.addWidget(self.rootView, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.gridLayout_7.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.faultWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem5 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.label_9 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_14.addWidget(self.label_9)
        spacerItem6 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pattView_2 = QChartView(self.page_6)
        self.pattView_2.setObjectName("pattView_2")
        self.gridLayout_6.addWidget(self.pattView_2, 0, 0, 1, 1)
        self.posiView_2 = QChartView(self.page_6)
        self.posiView_2.setObjectName("posiView_2")
        self.gridLayout_6.addWidget(self.posiView_2, 0, 1, 1, 1)
        self.resultWidget_4 = QtWidgets.QListWidget(self.page_6)
        self.resultWidget_4.setMinimumSize(QtCore.QSize(150, 0))
        self.resultWidget_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.resultWidget_4.setObjectName("resultWidget_4")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.resultWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resultWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.resultWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resultWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.resultWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resultWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.resultWidget_4.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resultWidget_4.addItem(item)
        self.gridLayout_6.addWidget(self.resultWidget_4, 0, 2, 2, 1)
        self.reasonView_2 = QChartView(self.page_6)
        self.reasonView_2.setObjectName("reasonView_2")
        self.gridLayout_6.addWidget(self.reasonView_2, 1, 0, 1, 1)
        self.rootView_2 = QChartView(self.page_6)
        self.rootView_2.setObjectName("rootView_2")
        self.gridLayout_6.addWidget(self.rootView_2, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        self.gridLayout_9.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.faultWidget.addWidget(self.page_6)
        self.verticalLayout_7.addWidget(self.faultWidget)
        self.horizontalLayout_16.addLayout(self.verticalLayout_7)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_23.addWidget(self.stackedWidget)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_23)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1204, 30))
        self.menubar.setObjectName("menubar")
        self.file = QtWidgets.QMenu(self.menubar)
        self.file.setObjectName("file")
        self.view = QtWidgets.QMenu(self.menubar)
        self.view.setObjectName("view")
        self.tool = QtWidgets.QMenu(self.menubar)
        self.tool.setObjectName("tool")
        self.window = QtWidgets.QMenu(self.menubar)
        self.window.setObjectName("window")
        self.help = QtWidgets.QMenu(self.menubar)
        self.help.setObjectName("help")
        self.setup = QtWidgets.QMenu(self.menubar)
        self.setup.setObjectName("setup")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionFileOpen = QtWidgets.QAction(MainWindow)
        self.actionFileOpen.setObjectName("actionFileOpen")
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.file.addAction(self.actionOpenFile)
        self.menubar.addAction(self.file.menuAction())
        self.menubar.addAction(self.setup.menuAction())
        self.menubar.addAction(self.view.menuAction())
        self.menubar.addAction(self.tool.menuAction())
        self.menubar.addAction(self.window.menuAction())
        self.menubar.addAction(self.help.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.reliaWidget.setCurrentIndex(0)
        self.reliaResultWidget.setCurrentIndex(0)
        self.maintainWidget.setCurrentIndex(0)
        self.mtResultWidget.setCurrentIndex(0)
        self.faultWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "可靠性分析系统"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "可靠性分析"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "维修性分析"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "故障分析"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.manaDevButton.setText(_translate("MainWindow", "管理设备"))
        self.devComboBox.setItemText(0, _translate("MainWindow", "选择设备"))
        __sortingEnabled = self.devWidget.isSortingEnabled()
        self.devWidget.setSortingEnabled(False)
        item = self.devWidget.item(0)
        item.setText(_translate("MainWindow", "设备1信息"))
        item = self.devWidget.item(1)
        item.setText(_translate("MainWindow", "设备编号："))
        item = self.devWidget.item(3)
        item.setText(_translate("MainWindow", "设备型号："))
        item = self.devWidget.item(5)
        item.setText(_translate("MainWindow", "设备名称："))
        self.devWidget.setSortingEnabled(__sortingEnabled)
        self.devComboBox_2.setItemText(0, _translate("MainWindow", "选择设备"))
        __sortingEnabled = self.devWidget_2.isSortingEnabled()
        self.devWidget_2.setSortingEnabled(False)
        item = self.devWidget_2.item(0)
        item.setText(_translate("MainWindow", "设备2信息"))
        item = self.devWidget_2.item(1)
        item.setText(_translate("MainWindow", "设备编号："))
        item = self.devWidget_2.item(3)
        item.setText(_translate("MainWindow", "设备型号："))
        item = self.devWidget_2.item(5)
        item.setText(_translate("MainWindow", "设备名称："))
        self.devWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("MainWindow", "故障判断标准："))
        self.label_4.setText(_translate("MainWindow", "温差："))
        self.label_5.setText(_translate("MainWindow", "℃"))
        self.label_6.setText(_translate("MainWindow", "精度："))
        self.label_7.setText(_translate("MainWindow", "μm"))
        self.outputDataButton.setText(_translate("MainWindow", "导出数据"))
        self.loadButton.setText(_translate("MainWindow", "导入数据"))
        self.manaRecButton.setText(_translate("MainWindow", "管理记录"))
        self.saveButton.setText(_translate("MainWindow", "保存结果"))
        self.rawDataButton.setText(_translate("MainWindow", "原始数据可视化"))
        self.scatterButton.setText(_translate("MainWindow", "故障时间散点图"))
        self.reliaButton.setText(_translate("MainWindow", "可靠性分析"))
        self.label_10.setText(_translate("MainWindow", "选择轴向："))
        self.axisComboBox.setItemText(0, _translate("MainWindow", "X"))
        self.axisComboBox.setItemText(1, _translate("MainWindow", "Y"))
        self.axisComboBox.setItemText(2, _translate("MainWindow", "Z"))
        self.label_11.setText(_translate("MainWindow", "轴"))
        self.label.setText(_translate("MainWindow", "选择算法："))
        self.comboBox.setItemText(0, _translate("MainWindow", "最小二乘法"))
        self.comboBox.setItemText(1, _translate("MainWindow", "极大后验估计法"))
        self.nextResultButton.setText(_translate("MainWindow", "下一页"))
        __sortingEnabled = self.dev1ResultWidget.isSortingEnabled()
        self.dev1ResultWidget.setSortingEnabled(False)
        item = self.dev1ResultWidget.item(0)
        item.setText(_translate("MainWindow", "设备1分析结果"))
        item = self.dev1ResultWidget.item(1)
        item.setText(_translate("MainWindow", "尺度参数λ："))
        item = self.dev1ResultWidget.item(3)
        item.setText(_translate("MainWindow", "形状参数β："))
        item = self.dev1ResultWidget.item(5)
        item.setText(_translate("MainWindow", "MTBF："))
        item = self.dev1ResultWidget.item(7)
        item.setText(_translate("MainWindow", "当前时间/h："))
        item = self.dev1ResultWidget.item(9)
        item.setText(_translate("MainWindow", "概率分布值："))
        item = self.dev1ResultWidget.item(11)
        item.setText(_translate("MainWindow", "累积分布值："))
        item = self.dev1ResultWidget.item(13)
        item.setText(_translate("MainWindow", "可靠度："))
        item = self.dev1ResultWidget.item(15)
        item.setText(_translate("MainWindow", "失效率："))
        self.dev1ResultWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.dev2ResultWidget.isSortingEnabled()
        self.dev2ResultWidget.setSortingEnabled(False)
        item = self.dev2ResultWidget.item(0)
        item.setText(_translate("MainWindow", "设备2分析结果"))
        item = self.dev2ResultWidget.item(1)
        item.setText(_translate("MainWindow", "尺度参数λ："))
        item = self.dev2ResultWidget.item(3)
        item.setText(_translate("MainWindow", "形状参数β："))
        item = self.dev2ResultWidget.item(5)
        item.setText(_translate("MainWindow", "MTBF："))
        item = self.dev2ResultWidget.item(7)
        item.setText(_translate("MainWindow", "当前时间/h："))
        item = self.dev2ResultWidget.item(9)
        item.setText(_translate("MainWindow", "概率分布值："))
        item = self.dev2ResultWidget.item(11)
        item.setText(_translate("MainWindow", "累积分布值："))
        item = self.dev2ResultWidget.item(13)
        item.setText(_translate("MainWindow", "可靠度："))
        item = self.dev2ResultWidget.item(15)
        item.setText(_translate("MainWindow", "失效率："))
        self.dev2ResultWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.cmpResultWidget.isSortingEnabled()
        self.cmpResultWidget.setSortingEnabled(False)
        item = self.cmpResultWidget.item(0)
        item.setText(_translate("MainWindow", "比较分析结果"))
        item = self.cmpResultWidget.item(1)
        item.setText(_translate("MainWindow", "当前时间/h："))
        item = self.cmpResultWidget.item(3)
        item.setText(_translate("MainWindow", "可靠度："))
        item = self.cmpResultWidget.item(5)
        item.setText(_translate("MainWindow", "失效率："))
        item = self.cmpResultWidget.item(7)
        item.setText(_translate("MainWindow", "MTBF："))
        self.cmpResultWidget.setSortingEnabled(__sortingEnabled)
        self.manaMtRecButton.setText(_translate("MainWindow", "管理记录"))
        self.loadButton_2.setText(_translate("MainWindow", "导入数据"))
        self.outputDataButton_2.setText(_translate("MainWindow", "导出数据"))
        self.scatterButton_2.setText(_translate("MainWindow", "维修时间散点图"))
        self.reliaButton_2.setText(_translate("MainWindow", "维修性分析"))
        self.saveButton_2.setText(_translate("MainWindow", "保存结果"))
        self.label_2.setText(_translate("MainWindow", "选择算法："))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "最小二乘法"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "极大后验估计法"))
        self.nextMtResultButton.setText(_translate("MainWindow", "下一页"))
        __sortingEnabled = self.dev1MtResultWidget.isSortingEnabled()
        self.dev1MtResultWidget.setSortingEnabled(False)
        item = self.dev1MtResultWidget.item(0)
        item.setText(_translate("MainWindow", "设备1分析结果"))
        item = self.dev1MtResultWidget.item(1)
        item.setText(_translate("MainWindow", "尺度参数λ："))
        item = self.dev1MtResultWidget.item(3)
        item.setText(_translate("MainWindow", "形状参数β："))
        item = self.dev1MtResultWidget.item(5)
        item.setText(_translate("MainWindow", "MTTR："))
        item = self.dev1MtResultWidget.item(7)
        item.setText(_translate("MainWindow", "维修时间/h："))
        item = self.dev1MtResultWidget.item(9)
        item.setText(_translate("MainWindow", "概率分布值："))
        item = self.dev1MtResultWidget.item(11)
        item.setText(_translate("MainWindow", "累积分布值："))
        item = self.dev1MtResultWidget.item(13)
        item.setText(_translate("MainWindow", "修复率："))
        item = self.dev1MtResultWidget.item(15)
        item.setText(_translate("MainWindow", "失效率："))
        self.dev1MtResultWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.dev2MtResultWidget.isSortingEnabled()
        self.dev2MtResultWidget.setSortingEnabled(False)
        item = self.dev2MtResultWidget.item(0)
        item.setText(_translate("MainWindow", "设备2分析结果"))
        item = self.dev2MtResultWidget.item(1)
        item.setText(_translate("MainWindow", "尺度参数λ："))
        item = self.dev2MtResultWidget.item(3)
        item.setText(_translate("MainWindow", "形状参数β："))
        item = self.dev2MtResultWidget.item(5)
        item.setText(_translate("MainWindow", "MTTR："))
        item = self.dev2MtResultWidget.item(7)
        item.setText(_translate("MainWindow", "维修时间/h："))
        item = self.dev2MtResultWidget.item(9)
        item.setText(_translate("MainWindow", "概率分布值："))
        item = self.dev2MtResultWidget.item(11)
        item.setText(_translate("MainWindow", "累积分布值："))
        item = self.dev2MtResultWidget.item(13)
        item.setText(_translate("MainWindow", "修复率："))
        item = self.dev2MtResultWidget.item(15)
        item.setText(_translate("MainWindow", "失效率："))
        self.dev2MtResultWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.cmpMtResultWidget.isSortingEnabled()
        self.cmpMtResultWidget.setSortingEnabled(False)
        item = self.cmpMtResultWidget.item(0)
        item.setText(_translate("MainWindow", "比较分析结果"))
        item = self.cmpMtResultWidget.item(1)
        item.setText(_translate("MainWindow", "当前时间/h："))
        item = self.cmpMtResultWidget.item(3)
        item.setText(_translate("MainWindow", "修复率："))
        item = self.cmpMtResultWidget.item(5)
        item.setText(_translate("MainWindow", "失效率："))
        item = self.cmpMtResultWidget.item(7)
        item.setText(_translate("MainWindow", "MTTR："))
        self.cmpMtResultWidget.setSortingEnabled(__sortingEnabled)
        self.addDataButton_3.setText(_translate("MainWindow", "添加记录"))
        self.loadButton_3.setText(_translate("MainWindow", "导入数据"))
        self.outputDataButton_3.setText(_translate("MainWindow", "导出数据"))
        self.wholeButton.setText(_translate("MainWindow", "整机分析"))
        self.subSysButton.setText(_translate("MainWindow", "子系统分析"))
        self.saveButton_3.setText(_translate("MainWindow", "保存结果"))
        self.label_8.setText(_translate("MainWindow", "整机分析"))
        __sortingEnabled = self.resultWidget_3.isSortingEnabled()
        self.resultWidget_3.setSortingEnabled(False)
        item = self.resultWidget_3.item(0)
        item.setText(_translate("MainWindow", "故障模式："))
        item = self.resultWidget_3.item(2)
        item.setText(_translate("MainWindow", "故障部位："))
        item = self.resultWidget_3.item(4)
        item.setText(_translate("MainWindow", "故障原因："))
        item = self.resultWidget_3.item(6)
        item.setText(_translate("MainWindow", "故障溯源："))
        self.resultWidget_3.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("MainWindow", "子系统分析"))
        __sortingEnabled = self.resultWidget_4.isSortingEnabled()
        self.resultWidget_4.setSortingEnabled(False)
        item = self.resultWidget_4.item(0)
        item.setText(_translate("MainWindow", "故障模式："))
        item = self.resultWidget_4.item(2)
        item.setText(_translate("MainWindow", "故障部位："))
        item = self.resultWidget_4.item(4)
        item.setText(_translate("MainWindow", "故障原因："))
        item = self.resultWidget_4.item(6)
        item.setText(_translate("MainWindow", "故障溯源："))
        self.resultWidget_4.setSortingEnabled(__sortingEnabled)
        self.file.setTitle(_translate("MainWindow", "文件"))
        self.view.setTitle(_translate("MainWindow", "视图"))
        self.tool.setTitle(_translate("MainWindow", "工具"))
        self.window.setTitle(_translate("MainWindow", "窗口"))
        self.help.setTitle(_translate("MainWindow", "帮助"))
        self.setup.setTitle(_translate("MainWindow", "设置"))
        self.actionLoad.setText(_translate("MainWindow", "load"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionFileOpen.setText(_translate("MainWindow", "fileOpen"))
        self.actionOpenFile.setText(_translate("MainWindow", "打开"))


