# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'record_list.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manaRecDialog(object):
    def setupUi(self, manaRecDialog):
        manaRecDialog.setObjectName("manaRecDialog")
        manaRecDialog.resize(972, 678)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(manaRecDialog)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prevButton = QtWidgets.QPushButton(manaRecDialog)
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout.addWidget(self.prevButton)
        self.nextButton = QtWidgets.QPushButton(manaRecDialog)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.switchPageLabel = QtWidgets.QLabel(manaRecDialog)
        self.switchPageLabel.setObjectName("switchPageLabel")
        self.horizontalLayout.addWidget(self.switchPageLabel)
        self.switchPageLineEdit = QtWidgets.QLineEdit(manaRecDialog)
        self.switchPageLineEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.switchPageLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.switchPageLineEdit.setObjectName("switchPageLineEdit")
        self.horizontalLayout.addWidget(self.switchPageLineEdit)
        self.pageLabel = QtWidgets.QLabel(manaRecDialog)
        self.pageLabel.setObjectName("pageLabel")
        self.horizontalLayout.addWidget(self.pageLabel)
        self.switchPageButton = QtWidgets.QPushButton(manaRecDialog)
        self.switchPageButton.setObjectName("switchPageButton")
        self.horizontalLayout.addWidget(self.switchPageButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.devComboBox = QtWidgets.QComboBox(manaRecDialog)
        self.devComboBox.setObjectName("devComboBox")
        self.devComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.devComboBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addDataButton = QtWidgets.QPushButton(manaRecDialog)
        self.addDataButton.setObjectName("addDataButton")
        self.horizontalLayout_2.addWidget(self.addDataButton)
        self.updateButton = QtWidgets.QPushButton(manaRecDialog)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout_2.addWidget(self.updateButton)
        self.delBatchButton = QtWidgets.QPushButton(manaRecDialog)
        self.delBatchButton.setObjectName("delBatchButton")
        self.horizontalLayout_2.addWidget(self.delBatchButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableView = QtWidgets.QTableView(manaRecDialog)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(manaRecDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.totalPagesLabel = QtWidgets.QLabel(manaRecDialog)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.totalPagesLabel.setFont(font)
        self.totalPagesLabel.setObjectName("totalPagesLabel")
        self.horizontalLayout_4.addWidget(self.totalPagesLabel)
        self.pageLabel_2 = QtWidgets.QLabel(manaRecDialog)
        self.pageLabel_2.setObjectName("pageLabel_2")
        self.horizontalLayout_4.addWidget(self.pageLabel_2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(manaRecDialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.currPageLabel = QtWidgets.QLabel(manaRecDialog)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.currPageLabel.setFont(font)
        self.currPageLabel.setObjectName("currPageLabel")
        self.horizontalLayout_5.addWidget(self.currPageLabel)
        self.pageLabel_3 = QtWidgets.QLabel(manaRecDialog)
        self.pageLabel_3.setObjectName("pageLabel_3")
        self.horizontalLayout_5.addWidget(self.pageLabel_3)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(618, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout)

        self.retranslateUi(manaRecDialog)
        QtCore.QMetaObject.connectSlotsByName(manaRecDialog)

    def retranslateUi(self, manaRecDialog):
        _translate = QtCore.QCoreApplication.translate
        manaRecDialog.setWindowTitle(_translate("manaRecDialog", "运行记录列表"))
        self.prevButton.setText(_translate("manaRecDialog", "上一页"))
        self.nextButton.setText(_translate("manaRecDialog", "下一页"))
        self.switchPageLabel.setText(_translate("manaRecDialog", "转到第"))
        self.pageLabel.setText(_translate("manaRecDialog", "页"))
        self.switchPageButton.setText(_translate("manaRecDialog", "Go"))
        self.devComboBox.setItemText(0, _translate("manaRecDialog", "选择设备"))
        self.addDataButton.setText(_translate("manaRecDialog", "添加记录"))
        self.updateButton.setText(_translate("manaRecDialog", "提交修改"))
        self.delBatchButton.setText(_translate("manaRecDialog", "批量删除"))
        self.label_3.setText(_translate("manaRecDialog", "总共"))
        self.totalPagesLabel.setText(_translate("manaRecDialog", "0"))
        self.pageLabel_2.setText(_translate("manaRecDialog", "页"))
        self.label_6.setText(_translate("manaRecDialog", "当前第"))
        self.currPageLabel.setText(_translate("manaRecDialog", "0"))
        self.pageLabel_3.setText(_translate("manaRecDialog", "页"))


